id: I61224639
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:07:32+00:00'
last_modified: '2022-06-08T03:26:35.961700+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5965
  title: རྒྱལ་པོ་ལུགས་ཀྱི་བསྟན་བཅོས་ས་གཞི་སྐྱོང་བའི་རྒྱན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4542':
      image_group_id: I1KG5978
      title: ''
      total_pages: 186
      order: 1
      base_file: 4542.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
