id: P005488
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5965
  title: རྒྱལ་པོ་ལུགས་ཀྱི་བསྟན་བཅོས་ས་གཞི་སྐྱོང་བའི་རྒྱན་
  author: ''
  volumes:
    77feba07f65f4c0fb07e1de173970a89:
      image_group_id: I1KG5978
      title: ''
      volume_number: 1
      total_pages: 186
